In [17]:
import pandas as pd
from scipy.stats import f_oneway
import numpy as np

# Sample data with a datetime column
np.random.seed(42)  # for reproducibility
dates = pd.to_datetime(['24-03-2002', '15-07-2003', '01-11-2004', '28-02-2006', '10-06-2007','10-06-2009', '10-06-2011', '10-06-2013'], format='%d-%m-%Y')
data = {'datetime': dates,
        'value': np.random.randint(5, 20, size=len(dates))}  # Random values
df = pd.DataFrame(data)

# Set 'datetime' as the index
df = df.set_index('datetime')

# Define the batch size (e.g., 2 years)
batch_size = 3

In [18]:
# Create batches based on year
df['batch'] = df.index.year // batch_size

In [19]:
df

            value  batch
datetime
2002-03-24     11    667
2003-07-15      8    667
2004-11-01     17    668
2006-02-28     19    668
2007-06-10     15    669
2009-06-10     12    669
2011-06-10     17    670
2013-06-10      9    671

In [20]:
batch_groups = df.groupby('batch')['value'].apply(list)

In [21]:
batch_groups

batch
667     [11, 8]
668    [17, 19]
669    [15, 12]
670        [17]
671         [9]
Name: value, dtype: object

In [22]:
if len(batch_groups) >= 2:
    f_statistic, p_value = f_oneway(*batch_groups)
    print(f"F-statistic: {f_statistic}")
    print(f"p-value: {p_value}")
    if p_value < 0.05:
        print("Significant difference.")
    else:
        print("No significant difference.")
else:
    print("Not enough batches for ANOVA.")

print(df)

F-statistic: 7.159090909090909
p-value: 0.06884959427510987
No significant difference.
            value  batch
datetime
2002-03-24     11    667
2003-07-15      8    667
2004-11-01     17    668
2006-02-28     19    668
2007-06-10     15    669
2009-06-10     12    669
2011-06-10     17    670
2013-06-10      9    671

In [24]:
import pandas as pd
from scipy.stats import chi2_contingency

import pandas as pd
from scipy.stats import chi2_contingency

# Create a contingency table (observed frequencies)
observed = pd.DataFrame({
    'Action': [50, 30],  # 50 Males prefer Action, 30 Females prefer Action
    'Comedy': [20, 40]   # 20 Males prefer Comedy, 40 Females prefer Comedy
}, index=['Male', 'Female'])

print("Observed Contingency Table:\n", observed)

Observed Contingency Table:
         Action  Comedy
Male        50      20
Female      30      40

In [25]:
chi2, p, dof, expected = chi2_contingency(observed)

print("\nChi-Square Test of Independence:")
print(f"Chi-square statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected Contingency Table:\n", expected)

# Interpretation:
alpha = 0.05  # Significance level
if p < alpha:
    print("There is a significant association between gender and movie preference.")
else:
    print("There is no significant association between gender and movie preference.")

Chi-Square Test of Independence:
Chi-square statistic: 10.529166666666667
P-value: 0.0011750518530845063
Degrees of freedom: 1
Expected Contingency Table:
 [[40. 30.]
 [40. 30.]]
There is a significant association between gender and movie preference.

In [6]:
from math import sqrt
sqrt(36)

6.0

In [4]:
import pandas as pd
import numpy as np
pd.set_option('display.max_column', None)

In [5]:
df = pd.read_parquet('../data/merged_data/merged_data.parquet')

In [6]:
df

,customer_id,gender,age,under_30,senior_citizen,partner,dependents,number_of_dependents,married,country,state,city,zip_code,total_population,latitude,longitude,phone_service,internet_service,online_security,online_backup,device_protection,premium_tech_support,streaming_tv,streaming_movies,streaming_music,internet_type,contract,paperless_billing,payment_method,monthly_ charges,avg_monthly_long_distance_charges,total_charges,total_refunds,total_extra_data_charges,total_long_distance_charges,total_revenue,tenure,multiple_lines,avg_monthly_gb_download,unlimited_data,offer,referred_a_friend,number_of_referrals,satisfaction_score,cltv,customer_status,churn_score,churn_label,churn_value,churn_category,churn_reason
0,0002-ORFBO,Female,37,No,No,Yes,No,0,Yes,United States,California,Frazier Park,93225,4498,34.827662,-118.999073,Yes,Yes,No,Yes,No,Yes,Yes,No,No,Cable,One Year,Yes,Mailed check,65.60,42.39,593.30,0.00,0,381.51,974.81,9,No,16,Yes,None,Yes,2,3,2205,Stayed,65,No,0,Not Applicable,None
1,0003-MKNFE,Male,46,No,No,No,No,0,No,United States,California,Glendale,91206,31297,34.162515,-118.203869,Yes,Yes,No,No,No,No,No,Yes,Yes,Cable,Month-to-Month,No,Mailed check,59.90,10.69,542.40,38.33,10,96.21,610.28,9,Yes,10,No,None,No,0,5,5414,Stayed,66,No,0,Not Applicable,None
2,0004-TLHLJ,Male,50,No,No,No,No,0,No,United States,California,Costa Mesa,92627,62069,33.645672,-117.922613,Yes,Yes,No,No,Yes,No,No,No,No,Fiber Optic,Month-to-Month,Yes,Electronic check,73.90,33.65,280.85,0.00,0,134.60,415.45,4,No,30,Yes,Offer E,No,0,1,4479,Churned,71,Yes,1,Competitor,Competitor had better devices
3,0011-IGKFF,Male,78,No,Yes,Yes,No,0,Yes,United States,California,Martinez,94553,46677,38.014457,-122.115432,Yes,Yes,No,Yes,Yes,No,Yes,Yes,No,Fiber Optic,Month-to-Month,Yes,Electronic check,98.00,27.82,1237.85,0.00,0,361.66,1599.51,13,No,4,Yes,Offer D,Yes,1,1,3714,Churned,91,Yes,1,Dissatisfaction,Product dissatisfaction
4,0013-EXCHZ,Female,75,No,Yes,Yes,No,0,Yes,United States,California,Camarillo,93010,42853,34.227846,-119.079903,Yes,Yes,No,No,No,Yes,Yes,No,No,Fiber Optic,Month-to-Month,Yes,Mailed check,83.90,7.38,267.40,0.00,0,22.14,289.54,3,No,11,Yes,None,Yes,3,1,3464,Churned,68,Yes,1,Dissatisfaction,Network reliability
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,9987-LUTYD,Female,20,Yes,No,No,No,0,No,United States,California,La Mesa,91941,44652,32.759327,-116.997260,Yes,Yes,Yes,No,No,Yes,No,No,Yes,DSL,One Year,No,Mailed check,55.15,46.68,742.90,0.00,0,606.84,1349.74,13,No,59,Yes,Offer D,No,0,4,3161,Stayed,59,No,0,Not Applicable,None
7039,9992-RRAMN,Male,40,No,No,Yes,No,0,Yes,United States,California,Riverbank,95367,16525,37.734971,-120.954271,Yes,Yes,No,No,No,No,No,Yes,Yes,Fiber Optic,Month-to-Month,Yes,Electronic check,85.10,16.20,1873.70,0.00,0,356.40,2230.10,22,Yes,17,Yes,Offer D,Yes,1,1,5248,Churned,68,Yes,1,Dissatisfaction,Product dissatisfaction
7040,9992-UJOEL,Male,22,Yes,No,No,No,0,No,United States,California,Elk,95432,383,39.108252,-123.645121,Yes,Yes,No,Yes,No,No,No,No,No,DSL,Month-to-Month,Yes,Mailed check,50.30,18.62,92.75,0.00,0,37.24,129.99,2,No,51,Yes,Offer E,No,0,5,5870,Joined,33,No,0,Not Applicable,None
7041,9993-LHIEB,Male,21,Yes,No,Yes,No,0,Yes,United States,California,Solana Beach,92075,12173,33.001813,-117.263628,Yes,Yes,Yes,No,Yes,Yes,No,Yes,Yes,Cable,Two Year,No,Mailed check,67.85,2.12,4627.65,0.00,0,142.04,4769.69,67,No,58,Yes,Offer A,Yes,5,3,4792,Stayed,59,No,0,Not Applicable,None
7042,9995-HOTOH,Male,36,No,No,Yes,No,0,Yes,United States,California,Sierra City,96125,348,39.600599,-120.636358,No,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Cable,Two Year,No,Electronic check,59.00,0.00,3707.60,0.00,0,0.00,3707.60,63,No,5,Yes,None,Yes,1,3,5639,Stayed,20,No,0,Not Applicable,None

#### <span style = 'color:skyblue'>gender
#### <span style = 'color:skyblue'>under_30, senior_citizen
#### <span style = 'color:skyblue'>married, partner, senior_citizen
#### <span style = 'color:skyblue'>phone_service, internet_service, online_security, online_backup, device_protection, premium_tech_support, streaming_tv, streaming_movies, streaming_music
#### <span style = 'color:skyblue'>internet_type
#### <span style = 'color:skyblue'>contract
#### <span style = 'color:skyblue'>cltv

In [10]:
df.head()

,customer_id,gender,age,under_30,senior_citizen,partner,dependents,number_of_dependents,married,country,state,city,zip_code,total_population,latitude,longitude,phone_service,internet_service,online_security,online_backup,device_protection,premium_tech_support,streaming_tv,streaming_movies,streaming_music,internet_type,contract,paperless_billing,payment_method,monthly_ charges,avg_monthly_long_distance_charges,total_charges,total_refunds,total_extra_data_charges,total_long_distance_charges,total_revenue,tenure,multiple_lines,avg_monthly_gb_download,unlimited_data,offer,referred_a_friend,number_of_referrals,satisfaction_score,cltv,customer_status,churn_score,churn_label,churn_value,churn_category,churn_reason
0,0002-ORFBO,Female,37,No,No,Yes,No,0,Yes,United States,California,Frazier Park,93225,4498,34.827662,-118.999073,Yes,Yes,No,Yes,No,Yes,Yes,No,No,Cable,One Year,Yes,Mailed check,65.6,42.39,593.30,0.00,0,381.51,974.81,9,No,16,Yes,None,Yes,2,3,2205,Stayed,65,No,0,Not Applicable,None
1,0003-MKNFE,Male,46,No,No,No,No,0,No,United States,California,Glendale,91206,31297,34.162515,-118.203869,Yes,Yes,No,No,No,No,No,Yes,Yes,Cable,Month-to-Month,No,Mailed check,59.9,10.69,542.40,38.33,10,96.21,610.28,9,Yes,10,No,None,No,0,5,5414,Stayed,66,No,0,Not Applicable,None
2,0004-TLHLJ,Male,50,No,No,No,No,0,No,United States,California,Costa Mesa,92627,62069,33.645672,-117.922613,Yes,Yes,No,No,Yes,No,No,No,No,Fiber Optic,Month-to-Month,Yes,Electronic check,73.9,33.65,280.85,0.00,0,134.60,415.45,4,No,30,Yes,Offer E,No,0,1,4479,Churned,71,Yes,1,Competitor,Competitor had better devices
3,0011-IGKFF,Male,78,No,Yes,Yes,No,0,Yes,United States,California,Martinez,94553,46677,38.014457,-122.115432,Yes,Yes,No,Yes,Yes,No,Yes,Yes,No,Fiber Optic,Month-to-Month,Yes,Electronic check,98.0,27.82,1237.85,0.00,0,361.66,1599.51,13,No,4,Yes,Offer D,Yes,1,1,3714,Churned,91,Yes,1,Dissatisfaction,Product dissatisfaction
4,0013-EXCHZ,Female,75,No,Yes,Yes,No,0,Yes,United States,California,Camarillo,93010,42853,34.227846,-119.079903,Yes,Yes,No,No,No,Yes,Yes,No,No,Fiber Optic,Month-to-Month,Yes,Mailed check,83.9,7.38,267.40,0.00,0,22.14,289.54,3,No,11,Yes,None,Yes,3,1,3464,Churned,68,Yes,1,Dissatisfaction,Network reliability

In [8]:
df.internet_type.fillna(method='ffill', axis=0, inplace=True)
df.internet_type.fillna(method='bfill', axis=0, inplace=True)

# <span style=color:lime> gender

In [46]:
gender_group = df.groupby('gender')[['avg_monthly_gb_download', 'total_revenue', 'cltv', 'churn_value']].sum()
gender_group

        avg_monthly_gb_download  total_revenue      cltv  churn_value
gender
Female                    72569    10552361.99  15376770          939
Male                      71921    10818769.70  15614513          930

In [47]:
gender_churn = df.pivot_table(index=['gender', 'internet_type'], columns=['churn_value'], aggfunc='size')
gender_churn

churn_value              0    1
gender internet_type
Female Cable           428  109
       DSL             840  159
       Fiber Optic    1281  671
Male   Cable           398  116
       DSL             889  180
       Fiber Optic    1338  634

In [49]:
contingency_table = pd.crosstab(df['gender'], df['internet_type'])
contingency_table

internet_type  Cable   DSL  Fiber Optic
gender
Female           537   999         1952
Male             514  1069         1972

In [23]:
contingency_table

internet_type  Cable   DSL  Fiber Optic
gender
Female           537   999         1952
Male             514  1069         1972

# <span style = 'color:red'> there's not significant difference in gender

# <span style=color:lime> under_30

In [57]:
under30_group = df.groupby('under_30')[['churn_value','avg_monthly_gb_download', 'total_revenue', 'cltv']]
under30_group.sum()

          churn_value  avg_monthly_gb_download  total_revenue      cltv
under_30
No               1565                    85749    17213104.06  24854284
Yes               304                    58741     4158027.63   6136999

In [55]:
under30_churn = pd.crosstab(df['under_30'], df['churn_value'])
under30_churn

churn_value     0     1
under_30
No           4077  1565
Yes          1097   304

In [58]:
under30_internet = pd.crosstab(df['under_30'], df['internet_type'])
under30_internet

internet_type  Cable   DSL  Fiber Optic
under_30
No               832  1615         3195
Yes              219   453          729

In [59]:
df.under_30.value_counts()

under_30
No     5642
Yes    1401
Name: count, dtype: int64

# <span style = 'color:red'> under_30 has low number across ['churn_value', 'avg_gb_download', 'revenue', 'cltv'] as the under_30 data is unblanced

# <span style=color:lime> senior_citizen

In [60]:
senior_group = df.groupby('senior_citizen')[['churn_value','avg_monthly_gb_download', 'total_revenue', 'cltv']]
senior_group.sum()

                churn_value  avg_monthly_gb_download  total_revenue      cltv
senior_citizen
No                     1393                   126461    17275804.21  25975871
Yes                     476                    18029     4095327.48   5015412

In [63]:
senior_churn = pd.crosstab(df['senior_citizen'], df['churn_value'])
senior_churn

churn_value        0     1
senior_citizen
No              4508  1393
Yes              666   476

In [76]:
senior_internet = pd.crosstab(df['senior_citizen'], df['internet_type'])
senior_internet

internet_type   Cable   DSL  Fiber Optic
senior_citizen
No                949  1867         3085
Yes               102   201          839

In [61]:
df.senior_citizen.value_counts()

senior_citizen
No     5901
Yes    1142
Name: count, dtype: int64

# <span style = 'color:red'>senior citizen data is also baised and unbalanced

# <span style=color:lime> between 30 and 65

In [74]:
df['30-65'] = df.apply(lambda x: 'Yes' if (x['under_30']=='No' and x['senior_citizen']=='No') else 'No', axis=1) # senior_citizen start after 65

In [75]:
between_group = df.groupby('30-65')[['churn_value','avg_monthly_gb_download', 'total_revenue', 'cltv']]
between_group.sum()

       churn_value  avg_monthly_gb_download  total_revenue      cltv
30-65
No             780                    76770     8253355.11  11152411
Yes           1089                    67720    13117776.58  19838872

### <span style = 'color:red'>even tho they have less avg_monthly_gb_download the revenue and cltv is high and churn_value

In [77]:
between_internet = pd.crosstab(df['30-65'], df['internet_type'])
between_internet

internet_type  Cable   DSL  Fiber Optic
30-65
No               321   654         1568
Yes              730  1414         2356

## <span style='color:red'> yup cuz of the between age people used the fiber_optics most with other also superior in bwtween age people group
## <span style='color:red'> these group people used most services but have used less avg_monthly_download thus they have satyed for long let's check that

In [80]:
between_tenure = pd.crosstab(df['30-65'], df['tenure'])
between_tenure

tenure,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72
30-65,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
No,4,205,90,71,68,48,35,52,50,35,37,34,30,37,29,36,30,30,37,23,30,25,30,30,36,29,31,33,20,27,25,22,30,28,26,30,19,29,21,17,20,28,20,22,18,22,27,27,23,24,24,24,28,22,26,27,31,21,20,20,31,31,24,22,29,33,34,36,27,36,45,70,132
Yes,7,408,148,129,108,85,75,79,73,84,79,65,87,72,47,63,50,57,60,50,41,38,60,55,58,50,48,39,37,45,47,43,39,36,39,58,31,36,38,39,44,42,45,43,33,39,47,41,41,42,44,44,52,48,42,37,49,44,47,40,45,45,46,50,51,43,55,62,73,59,74,100,230

In [81]:
between_tenure_group = df.groupby('30-65')['tenure'].sum()
between_tenure_group

30-65
No      83336
Yes    144654
Name: tenure, dtype: int64

# <span style='color:red'> hence they used the services longer than others groups

# <span style=color:lime> mairred and partner

In [84]:
df.partner.value_counts()

partner
No     3641
Yes    3402
Name: count, dtype: int64

In [85]:
df.married.value_counts()

married
No     3641
Yes    3402
Name: count, dtype: int64

In [87]:
(df.partner == df.married).all()

True

## <span style=color:red> both are same

In [90]:
married_group = pd.crosstab(df['senior_citizen'], df['married'])
married_group

married           No   Yes
senior_citizen
No              3072  2829
Yes              569   573

In [92]:
#not so strong relation proly cuz of unbalanced data of senior citizen

In [93]:
married_group = pd.crosstab(df['30-65'], df['married'])
married_group

married    No   Yes
30-65
No       1272  1271
Yes      2369  2131

# <span style = color:red> the age group senior and between does not have any significant difference on married

# <span style = color:lime> service

In [94]:
print(df.phone_service.value_counts(), df.internet_service.value_counts(), df.online_security.value_counts(), df.online_backup.value_counts(), df.device_protection.value_counts(), df.premium_tech_support.value_counts(), df.streaming_tv.value_counts(), df.streaming_movies.value_counts(), df.streaming_music.value_counts(), sep='\n')

phone_service
Yes    6361
No      682
Name: count, dtype: int64
internet_service
Yes    5517
No     1526
Name: count, dtype: int64
online_security
No     5024
Yes    2019
Name: count, dtype: int64
online_backup
No     4614
Yes    2429
Name: count, dtype: int64
device_protection
No     4621
Yes    2422
Name: count, dtype: int64
premium_tech_support
No     4999
Yes    2044
Name: count, dtype: int64
streaming_tv
No     4336
Yes    2707
Name: count, dtype: int64
streaming_movies
No     4311
Yes    2732
Name: count, dtype: int64
streaming_music
No     4555
Yes    2488
Name: count, dtype: int64